sudo: required
language: python
install:
- sudo apt-get update
- sudo update-ca-certificates
script:
- git diff --name-only $TRAVIS_COMMIT_RANGE | python validate.py
env:
  secure: SAhfNB5pek/No6kJAU7NNdtqy4a2tSH4+9yXEE+ir+Ct81cSIjnCVfXbULpxWJDe68iRkWZrnZZ40GvGE//wqcE9h5JcF09zvyyzP1ZzCf0OpnH2EXMEEa5RA8u/Zhrvvibc0hUXk8Q8xT+2Ew9wpY/OPIeNNQrncp7DYxTy5z1iHDTC7LUC/eeuoJ+utDmU59EFTOdLA5COokxMlh2/ng0LlDQLAY7j8cC4JBSBMongVY+hw0oUUvTIhesSZbmZttYayVZul8zfFA+YNbm1XKgtPfH/gwM396k7zp6wqKqSgoVa6o7H8xxMgXjaS9mEZvM10PnbVRsguyfAyo7kNy8L0kJy4/am0Y8APmEoqOD6l03jciqyPU6SWleYMyP3UtEwRx5VSif8YCKRsHrKSSWyJOKZuvegVymxTT0h9A2BTdCHPUS2RLOBAW6G3a+J2i5uA5zur+gnm2hL8H7c4ef7I22yXTGp4JAC31j3qcEQYo7kHPCw2JZ5btCMaeuJ9Qfc2F72Eh0L5BV4iewMMzcysH7cBmn+pND1SO3046KYVD/+0toAWHbomOGIFhDmnVeKdnG7Bjcxua8ADVJpCyhNNCd9dkgYq3jgz+plCOd+AqVhjgqjMOx+Dq+aRzOD42JZ1C+snCBaPTlBUpO+wj1EaxNO96HE2qmufr0NdMA=
