sudo: required
language: python
install:
- sudo apt-get update
- sudo update-ca-certificates
script:
- pip install requests
- git diff --name-only $TRAVIS_COMMIT_RANGE | python validate.py
env:
  secure: u5bmmRempnc15dVn18ubQKbZDuh1F99fLDGyVxHCUzFAgeDvc8SjoLNpB3pE0D4bpYe+rr8IpQESYSaaEWILb6r3lLZzNSxU+pcSAYnCN80TCmRsFmDqTwf9l1Ulo6dLGbbkhdCnrEyjIsNHc8FYZV3in92wQzFTluCdNAPGXBoky+hlwYILp6WbhOLb4WCk1wRXzgGymi4zID1b8rIsbar5gT6u/Kc7CUO2grAtliurJbtGIgFT3L1OChTQx4sCPNZaN9/K/eXkTp7Pd+t+15JeO5ohmJdgwap0IjD32vRdpB17kGEXmng169I6nfJKaA5ic8BvM9s7Di5TV0lLiVTZ+SBZtWOMekp9bnwF430PG4ZhDSaM8za7tKWtkeK9CdMJ2K4jaQYM7s8eVkf/6OtjIGHp4Yy2hNIDHLt+0OU7emTvAXKm7Tait/cI8Fh6bAjg/0AK2NKnmlyRV58uvJCMu6UtLXTMZs41wgH+++OexaGkrYRVtsveAxIgMSKzi19BswtAFZPr+e5GNUEwbEl+b0BX9EyzNpNRaFTogU1pN1OYMTPk965QPAsYp1J37VVlARw7+s0s/sfibZLvkszAqHvIGAJiknoG3xSIQyMZix9fvBBkE7o2d1MsfF700Yfcwovs14t0fwLFpiyTuvnlGO4S4BPqFk/EjXW9Bxc=
