sudo: required
language: python
install:
- sudo apt-get update
- sudo update-ca-certificates
script:
- pip install requests
- git diff --name-only $TRAVIS_COMMIT_RANGE | python validate.py
env:
  - secure: "DIa95ZHAAN/btUZe1mwlSmxVrHx+gZ8nkbwPalW3fEt9sa9IlvzNS0RWoVkt/LKp7fX8ffYzTCItYUMpBni0JAIW9Lu1YamnCUJzAYCAJVFHuGahhWlMJKTxFYlfwPIaXB7uUd4K2z1/qxJAAbBfGjsHo8laIxmNE74zyyCySiedSTqfegsLMsMXZaiElBJlkc77hOeL1hTU4uF/ScPXV/dJd1mT2Xc9ekPw3qf40VfUS3mInyd1Vt6eOTRO3L9zfpkpM7jRloHOFlBDl9Cxkc2qr4LSbdvuEsB3eALqkz0l5HKa75epkTYLTakjf3lKT0zVjfZI/rSEGkNNjmbCDFWPqFwGrYS51FpTaTouqhFRq9x4pixWBK0q6i93yAfwuPksdarrFsR2D8FTh8O/F6bzI8MMrBf5fikxPb7GC+ZFNodxzrAs5YpxFkSY0EykgogHe1ZreiABEjX3nm/MrMJE5YJVQLeERkR+QxuNYbL9HFnN5eSo5IrBkKqF9IuDkkDe71Ae9vbRNAim3ZjgF9pkFvyOn2mMJoRx+izNsx4J7peo2nGvM3wPHKXJSlVcbuHDnlrUboEYYa8rGinhSTCIkYLC9d6PCq52Ae75zbzfuzLjQ7o1eoYTKOjZJxQNqUWDUdSPg3AxZYuLEDuDXXxdbIJ8Z+GXmVeANc2E5hs="