package: conda-package-handling
distribution: debian
release: sid
component: main
version: 2.3.0
source: conda-package-handling
homepage: https://github.com/conda/conda-package-handling
license: unknown
blend: debian-med
description_md5: a5bdc754e78c3925e981f636826137fa
popcon:
- insts: 114
  olde: 94
  recent: 3
  vote: 17
descr:
- package: conda-package-handling
  description: creazione ed estrazione di pacchetti conda in vari formati
  long_description: " Cph è un'astrazione della gestione dei pacchetti conda e uno
    strumento per\n estrarre, creare e convertire tra formati.\n .\n Al momento della
    scrittura di questo testo, il formato standard di un\n pacchetto conda è un file
    .tar.bz2. Ciò dovrà essere mantenuto per un tempo\n piuttosto lungo, a causa dalla
    grande quantità di persone che usano ancora\n versioni vecchie di conda. Esiste
    un nuovo formato per conda, descritto in\n https://docs.google.com/document/d/1HGKsbg_j69rKXPihhpCb1kNQSE8Iy3yOsUU2x68x8uw/edit?usp=sharing.\n
    Questo nuovo formato è progettato per avere un accesso molto più veloce ai\n metadati
    e per utilizzare algoritmi di compressione più moderni,\n facilitando al contempo
    la firma dei pacchetti senza aggiungere file di\n accompagnamento.\n"
  release: sid
  description_md5: a5bdc754e78c3925e981f636826137fa
  license: unknown
  blend: debian-med
- package: conda-package-handling
  description: create and extract conda packages of various formats
  long_description: " Cph is an abstraction of conda package handling and a tool for\n
    extracting, creating, and converting between formats.\n .\n At the time of writing,
    the standard conda package format is a .tar.bz2\n file. That will need to be maintained
    for quite a long time, thanks to\n the long tail of people using old conda versions.
    There is a new conda\n format, described at https://docs.google.com/document/d/1HGKsbg_j69rKXP-\n
    ihhpCb1kNQSE8Iy3yOsUU2x68x8uw/edit?usp=sharing. This new format is\n designed
    to have much faster metadata access and utilize more modern\n compression algorithms,
    while also facilitating package signing without\n adding sidecar files.\n"
  release: sid
  description_md5: a5bdc754e78c3925e981f636826137fa
  license: unknown
  blend: debian-med
- package: conda-package-handling
  description: Opret og udtræk conda-pakker i diverse formater
  long_description: " Cph er en abstraktion af conda-pakkehåndtering og et værktøj
    for udtrækning, oprettelse og konvertering mellem formater.\n .\n På tidspunktet
    for denne tekst er condas pakkeformat en .tar.bz2-fil. Den vil blive vedligeholdt
    i lang tid, takket være den store mængde af folk, der bruger ældre conda-versioner.
    Der er et nyt conda-format, beskrevet her https://docs.google.com/document/d/1HGKsbg_j69rKXP-\n
    ihhpCb1kNQSE8Iy3yOsUU2x68x8uw/edit?usp=sharing. Dette nye format er designet til
    at have meget hurtigere adgang til metadata og udnytte mere moderne komprimeringsalgoritmer,
    mens der også faciliteres pakkeunderskrivning uden tilføjelse af sidecar-filer.\n"
  release: sid
  description_md5: a5bdc754e78c3925e981f636826137fa
  license: unknown
  blend: debian-med
- package: conda-package-handling
  description: création et extraction de paquets conda de différents formats
  long_description: " Cph est une abstraction de « conda package handling » et un
    outil pour\n extraire, créer et convertir des paquets de différents formats.\n
    .\n Au moment de cette écriture, le format standard de conda est un fichier\n
    .tar.bz2. Conda a été entretenu depuis longtemps, merci aux nombreuses\n personnes
    qui utilisent les anciennes versions de conda. Un nouveau format\n de conda, décrit
    sur https://docs.google.com/document/d/1HGKsbg_j69rKXP-\n ihhpCb1kNQSE8Iy3yOsUU2x68x8uw/edit?usp=sharing,
    existe. Ce nouveau format\n est conçu pour permettre un accès beaucoup plus rapide
    aux métadonnées et\n utilise des algorithmes de compression plus modernes, tout
    en facilitant\n la signature de paquet sans ajout de fichiers auxiliaires.\n"
  release: sid
  description_md5: a5bdc754e78c3925e981f636826137fa
  license: unknown
  blend: debian-med
