package: prodigal
distribution: debian
release: sid
component: main
version: 2.6.3
source: prodigal
homepage: http://prodigal.ornl.gov/
license: unknown
blend: debian-med
description_md5: 17547e924925fa3b22bf27a8a6cf1be5
registries:
- entry: OMICS_01493
  name: OMICtools
- entry: SCR_011936
  name: SciCrunch
- entry: prodigal
  name: conda:bioconda
bib:
- key: doi
  value: 10.1186/1471-2105-11-119
popcon:
- insts: 73
  olde: 63
  recent: 5
  vote: 5
descr:
- package: prodigal
  description: programma per trovare geni microbici (di batteri e archeobatteri)
  long_description: " Prodigal (Prokaryotic Dynamic Programming Genefinding Algorithm)
    è un\n programma per trovare geni microbici (di batteri e archeobatteri)\n sviluppato
    all'Oak Ridge National Laboratory dell'University of Tennessee.\n Le funzionalità
    principali di Prodigal includono:\n .\n Velocità: Prodigal è uno strumento estremamente
    veloce per il\n riconoscimento di geni (scritto in C molto standard). Può analizzare
    un\n intero genoma microbico in 30 secondi o meno.\n .\n Accuratezza: Prodigal
    trova geni in modo altamente accurato.\n Localizza correttamente il terminale
    3' di ogni gene nell'insieme dei dati\n Ecogene sperimentalmente verificato (tranne
    quelli che contengono introni).\n Possiede un sistema molto sofisticato di punteggi
    per i siti di legame con\n ribosomi che gli permette di localizzare il sito di
    inizio della traduzione\n con grande accuratezza (il 96% dei terminali 5' nell'insieme
    di dati\n Ecogene è correttamente localizzato).\n .\n Specificità: Il confronto
    di Prodigal con altri programmi di\n identificazione di geni è buono per ciò che
    riguarda il tasso di falsi\n positivi di Prodigal che di solito è inferiore al
    5%.\n .\n Insensibile al contenuto di GC: Prodigal dà buoni risultati anche in
    genomi\n con alto contenuto di GC, con più del 90% di corrispondenza perfetta\n
    (5'+3') rispetto alle annotazioni riviste di Pseudomonas aeruginosa.\n .\n Versione
    metagenomica: Prodigal può essere eseguito in modalità\n metagenomica e analizzare
    sequenze anche quando l'organismo è sconosciuto.\n .\n Facilità d'uso: Progigal
    può essere eseguito in un unico passaggio su\n un'unica sequenza genomica oppure
    su una bozza di genoma contenente molte\n sequenze. Non è necessario fornirgli
    alcuna conoscenza sull'organismo dato\n che apprende da solo tutte le proprietà
    di cui ha bisogno.\n"
  release: sid
  description_md5: 17547e924925fa3b22bf27a8a6cf1be5
  license: unknown
  blend: debian-med
- package: prodigal
  description: Microbial (bacterial and archaeal) gene finding program
  long_description: " Prodigal (Prokaryotic Dynamic Programming Genefinding Algorithm)
    is a\n microbial (bacterial and archaeal) gene finding program developed at\n
    Oak Ridge National Laboratory and the University of Tennessee.\n Key features
    of Prodigal include:\n .\n Speed: Prodigal is an extremely fast gene recognition
    tool\n (written in very vanilla C). It can analyze an entire microbial genome\n
    in 30 seconds or less.\n .\n Accuracy: Prodigal is a highly accurate gene finder.\n
    It correctly locates the 3' end of every gene in the experimentally verified\n
    Ecogene data set (except those containing introns).\n It possesses a very sophisticated
    ribosomal binding site scoring system that\n enables it to locate the translation
    initiation site with great accuracy\n (96% of the 5' ends in the Ecogene data
    set are located correctly).\n .\n Specificity: Prodigal's false positive rate
    compares favorably with other\n gene identification programs, and usually falls
    under 5%.\n .\n GC-Content Indifferent: Prodigal performs well even in high GC
    genomes,\n with over a 90% perfect match (5'+3') to the Pseudomonas aeruginosa
    curated\n annotations.\n .\n Metagenomic Version: Prodigal can run in metagenomic
    mode and analyze\n sequences even when the organism is unknown.\n .\n Ease of
    Use: Prodigal can be run in one step on a single genomic sequence\n or on a draft
    genome containing many sequences. It does not need to be\n supplied with any knowledge
    of the organism, as it learns all the properties\n it needs to on its own.\n"
  release: sid
  description_md5: 17547e924925fa3b22bf27a8a6cf1be5
  license: unknown
  blend: debian-med
- package: prodigal
  description: Mikrobiel (bakteriel og archaeorganisme) genkonstateringsprogram
  long_description: " Prodigal (Prokaryotisk Dynamic Programming Genefinding Algoritme)
    er et\n mikrobiel (bakteriel og archaeorganisme) genkonstateringsprogram udviklet\n
    på Oak Ridge National Laboratory og University of Tennessee.\n Nøglefunktioner
    i Prodigal inkluderer:\n .\n Hastighed: Prodigal er et ekstremt hurtigt gengenkendelsesværktøj\n
    (skrevet i very vanilla C). Det kan analysere et helt mikrobielt genom\n på 30
    sekunder eller mindre.\n .\n Nøjagtighed: Prodigal er en meget nøjagtig genfinder.\n
    Prodigal lokaliserer 3'-enden af hvert gen i eksperimentelt verificeret\n korrekte
    Ecogene-datasæt (undtagen dem, der indeholder introns).\n Prodigal besidder et
    meget sofistikeret\n ribosombindingssted-bedømmelsessystem, der gør det muligt
    at lokalisere\n translationsinitieringsstedet med stor nøjagtighed (96% af 5'-ender
    i\n Ecogene-datasættet er placeret korrekt).\n .\n Specificitet: Prodigal falske
    positive rate kan måle sig med andre\n genidentifikationsprogrammer, og falder
    normalt under 5 %.\n .\n GC-indhold Ligeglade: Prodigal klarer sig godt selv i
    høje GC-genomer,\n med over 90 % perfekt match (5'+3') til Pseudomonas aeruginosa
    kurateret\n annotationer.\n .\n Metagenomisk version: Prodigal kan køre i metagenomisk
    tilstand og\n analysere sekvenser, selv når organismen er ukendt.\n .\n Brugervenlighed:
    Prodigal kan køres i et trin på en enkelt genomisk sekvens\n eller på et udkastgenom
    der indeholder mange sekvenser. Det behøver ikke at\n være leveret med kendskab
    til organismen, da programmet lærer alle de\n egenskaber det skal på egen hånd.\n"
  release: sid
  description_md5: 17547e924925fa3b22bf27a8a6cf1be5
  license: unknown
  blend: debian-med
