package: proda
distribution: debian
release: sid
component: main
version: '1.0'
source: proda
homepage: http://proda.stanford.edu/
license: unknown
blend: debian-med
description_md5: a4af9732493dab9dac9eed761a23a635
registries:
- entry: OMICS_21692
  name: OMICtools
- entry: ProDA
  name: bio.tools
- entry: proda
  name: conda:bioconda
bib:
- key: doi
  value: 10.1093/nar/gkl511
tags:
- tag: biology::nuceleic-acids
- tag: biology::peptidic
- tag: field::biology
- tag: field::biology:bioinformatics
- tag: implemented-in::c++
- tag: interface::commandline
- tag: role::program
- tag: scope::utility
- tag: use::analysing
- tag: use::comparing
- tag: works-with-format::plaintext
- tag: works-with::TODO
popcon:
- insts: 183
  olde: 154
  recent: 13
  vote: 16
descr:
- package: proda
  description: 产生蛋白质序列的多种排序
  long_description: " ProDA 是自动探测和排列具有任意域结构的蛋白质集合的同源区域的系统。给定一个\n 未排列的序列，ProDA 确认出现在一个或多个序列的所有同源区域，并输出这些区域\n
    的本地多排序集合。\n"
  release: sid
  description_md5: a4af9732493dab9dac9eed761a23a635
  license: unknown
  blend: debian-med
- package: proda
  description: Proteiinisarjojen moninainen rivitys
  long_description: " ProDA on järjestelmä mielivaltaisten proteiinikokoelmien homologisten\n
    alueiden sijoittumisen tunnistamiseen.\n Kun syötetään sarja sekvenssejä, ProDA
    tunnistaa kaikki\n yhdessä tai useammassa sekvenssissä esiintyvät homologiset
    alueet ja\n tulostaa näiden alueiden sijaintitiedot.\n"
  release: sid
  description_md5: a4af9732493dab9dac9eed761a23a635
  license: unknown
  blend: debian-med
- package: proda
  description: multoblaj laŭliniigo de proteinaj sekvoj
  long_description: " ProDA estas sistemo por aŭtomata detekto kaj laŭliniigo de homologaj\n
    regionoj in kolektoj de proteinoj kun arbitraj dominiaj arkitekturoj.\n Donataj
    enigaroj de mallaŭliniigaj sekvoj, ProDA identigas ĉiujn homologajn\n regionojn
    aperantajn en unu aŭ pli da sekvoj, kaj redonas kolekton de\n multoblaj lokaj
    laŭliniigoj por tiuj regionoj.\n"
  release: sid
  description_md5: a4af9732493dab9dac9eed761a23a635
  license: unknown
  blend: debian-med
- package: proda
  description: meervoudige groepering van proteïnereeksen
  long_description: " ProDa is een systeem voor geautomatiseerde detectie en groeperen
    van\n homologe (gelijksoortige) gebieden in verzamelingen van proteïnen met\n
    willekeurige domeinarchitecturen. Gegeven een verzameling van\n ongegroepeerde
    reeksen als invoer, identificeert ProDA alle homologe\n gebieden die in een of
    meer reeksen voorkomen, en retourneert een\n verzameling van lokale meervoudige
    groeperingen voor deze gebieden.\n"
  release: sid
  description_md5: a4af9732493dab9dac9eed761a23a635
  license: unknown
  blend: debian-med
- package: proda
  description: 단백질 시퀀스의 다중 정열
  long_description: " ProDA는 임의의 도메인 구조를 갖는 단백질 모임에서 상응하는 영역을 자동으로\n 감지 및 정렬하기 위한
    시스템입니다. 정렬되지 않는 시퀀스 입력 집합이 주어지면,\n ProDA는 하나 이상의 시퀀스에 나타나는 모든 상응하는 지역을 식별하고, 그리고\n
    이들 지역에 대한 내부 다중 정렬의 모음을 반환합니다.\n"
  release: sid
  description_md5: a4af9732493dab9dac9eed761a23a635
  license: unknown
  blend: debian-med
- package: proda
  description: Комбінаційне розташування протеїнових послідовностей
  long_description: " ProDA - система для автоматизованого виявлення та розташування
    гомологених\n областей в наборах протеїнів з довільною базовою будовою. В отриманих\n
    неузгоджених послідовностях ProDA визначає усі гомологені області, що\n з'являються
    в одній або де-кількох послідовностях, та повертає набір\n локального комбінаційного
    розташування для них.\n"
  release: sid
  description_md5: a4af9732493dab9dac9eed761a23a635
  license: unknown
  blend: debian-med
- package: proda
  description: multipelgruppering av proteinsekvenser
  long_description: " ProDA är ett system för automatisk lokalisering och gruppering
    av homologa\n regioner i en samling proteiner med godtyckligt antal domänarkitekturer.\n
    Givet ett inmatat set med ogrupperade sekvenser identifierar ProDA samtliga\n
    homologa regioner som förekommer i en eller fler sekvenser, och returnerar\n en
    samling lokala multipelgrupperingar för dessa regioner.\n"
  release: sid
  description_md5: a4af9732493dab9dac9eed761a23a635
  license: unknown
  blend: debian-med
- package: proda
  description: タンパク質配列のマルチプルアライメント
  long_description: " ProDAは、任意のドメイン構造を持つタンパク質の集合に含まれる相同領域を、自動\n 的に検出し、アライメントを行うシステムです。アライメントされていない配列の\n
    集合を入力として与えると、ProDAは、1つ以上の配列に出現する相同領域を全て同\n 定し、これらの領域の局所多重アライメントの集合を返します。\n"
  release: sid
  description_md5: a4af9732493dab9dac9eed761a23a635
  license: unknown
  blend: debian-med
- package: proda
  description: Mulitple Alignments von Proteinsequenzen
  long_description: " ProDA ist ein System zur automatischen Erkennung und Anordnung
    von\n homologen Regionen in Proteinsammlungen mit beliebigen\n Domain-Architekturen.
    Bei gegebenem Eingangssatz von nicht-angeordneten\n Sequenzen identifiziert ProDA
    eine homologe Region, die in einer oder\n mehrere Sequenzen auftaucht und liefert
    eine Sammlung von lokalen\n multiplen Anordnungen für diese Regionen zurück.\n"
  release: sid
  description_md5: a4af9732493dab9dac9eed761a23a635
  license: unknown
  blend: debian-med
- package: proda
  description: alinhamento múltiplo de seqüências de proteína
  long_description: " ProDA é um sistema para detecção automática e alinhamento de
    regiões\n homólogas em coleções de proteína com arquiteturas de domínio arbitrário.\n
    Dado um conjunto de entrada de seqüências desalinhadas, o ProDA identifica\n todas
    as regiões homólogas que aparecem em uma ou mais seqüências, e\n retorna uma coleção
    de múltiplos alinhamentos locais para estas regiões.\n"
  release: sid
  description_md5: a4af9732493dab9dac9eed761a23a635
  license: unknown
  blend: debian-med
- package: proda
  description: viacnásobné zarovnanie proteínových sekvencií
  long_description: " ProDA je systém na automatickú detekciu a zarovnávanie homologických\n
    oblastí v zbierkach proteínov s ľubovoľnými doménovými architektúrami.\n Po zadaní
    vstupnej množiny nezarovnaných sekvencií ProDA identifikuje\n všetky homologické
    oblasti vyskytujúce sa v jednej alebo viacerých\n sekvenciách a vráti zbierku
    lokálnych viacnásobných zarovnaní v týchto\n oblastiach.\n"
  release: sid
  description_md5: a4af9732493dab9dac9eed761a23a635
  license: unknown
  blend: debian-med
- package: proda
  description: allineamento multiplo di sequenze proteiche
  long_description: " ProDA è un sistema per il rilevamento automatico e l'allineamento
    di\n regioni omologhe in insiemi di proteine con architetture di dominio\n arbitrarie.
    Dato un insieme di sequenze non allineate, ProDA identifica\n tutte le regioni
    omologhe che appaiono in una o più sequenze, e restituisce\n un insieme di allineamenti
    multipli locali per queste regioni.\n"
  release: sid
  description_md5: a4af9732493dab9dac9eed761a23a635
  license: unknown
  blend: debian-med
- package: proda
  description: hromadný alignment proteinových sekvencí
  long_description: " ProDA je systém pro automatickou detekci a alignment homologních
    úseků v\n souboru proteinů se známou doménovou architekturou. Ve vstupní sadě\n
    nealignovaných sekvencí ProDA najde všechny homologní úseky, které se\n vyskytují
    v jedné nebo ve více sekvencích, a vytvoří soubor lokálních\n násobných alignmentů
    pro tyto úseky.\n"
  release: sid
  description_md5: a4af9732493dab9dac9eed761a23a635
  license: unknown
  blend: debian-med
- package: proda
  description: Alinhamento múltiplo para sequencias de proteínas
  long_description: " ProDA é um sistema para detecção automática e alinhamento de
    regiões\n homólogas em colecções de proteínas com arquitecturas de domínio\n arbitrárias.
    Dada uma entrada de um conjunto de sequências não alinhadas, o\n ProDA identifica
    todas as regiões homólogas qua aparecem em uma ou mais\n sequências, e retorna
    uma colecção de alinhamentos múltiplos locais para\n essas regiões.\n"
  release: sid
  description_md5: a4af9732493dab9dac9eed761a23a635
  license: unknown
  blend: debian-med
- package: proda
  description: multiple alignment of protein sequences
  long_description: " ProDA is a system for automated detection and alignment of homologous\n
    regions in collections of proteins with arbitrary domain architectures.\n Given
    an input set of unaligned sequences, ProDA identifies all\n homologous regions
    appearing in one or more sequences, and returns a\n collection of local multiple
    alignments for these regions.\n"
  release: sid
  description_md5: a4af9732493dab9dac9eed761a23a635
  license: unknown
  blend: debian-med
- package: proda
  description: Wielokrotne wyrównywanie sekwencji białkowych
  long_description: " ProDA to system do automatycznego wykrywania i wyrównywania
    homologicznych\n regionów w zestawach białek o dowolnej domenowej architekturze.
    Po pobraniu\n wejściowego zestawu niewyrównanych sekwencji, ProDA identyfikuje
    wszystkie\n homologiczne regiony, pojawiające się w jednej lub większej liczbie\n
    sekwencji, i zwraca zbiór lokalnych wielokrotnych wyrównań dla tych regionów.\n"
  release: sid
  description_md5: a4af9732493dab9dac9eed761a23a635
  license: unknown
  blend: debian-med
- package: proda
  description: multi-sammenligning af protein-sekvenser
  long_description: " ProDA er et system til automatiseret detektering og sammenligning
    af\n homologe regioner i kollektioner af proteiner med arbitrære domæne-\n arkitekturer.
    Givent et input sæt af ikke-sammenlignede sekvenser, vil\n ProDA identificere
    alle homologe regioner som fremkommer i en eller flere\n sekvenser, og returnerer
    en kollektion af lokale flerjusteringer for\n disse regioner.\n"
  release: sid
  description_md5: a4af9732493dab9dac9eed761a23a635
  license: unknown
  blend: debian-med
- package: proda
  description: alineación múltiple de secuencias de proteínas
  long_description: " ProDA es un sistema para la detección automática y alineamiento
    de regiones\n homólogas en colecciones de proteínas con arquitecturas dominantes\n
    arbitrarias. Dado un conjunto de entrada de secuencias no alineadas, ProDA\n identifica
    todas las regiones homólogas que aparezcan en una o más\n secuencias, y devuelve
    una colección de alineaciones múltiples locales para\n estas regiones.\n"
  release: sid
  description_md5: a4af9732493dab9dac9eed761a23a635
  license: unknown
  blend: debian-med
- package: proda
  description: Alignement multiple de séquences protéiques
  long_description: " ProDA est un programme pour détecter et aligner les régions
    homologues\n dans des collections de protéines comportant divers arrangements
    de\n domaines. À partir d'un ensemble de séquences non alignées, ProDA\n identifiera
    toutes les régions homologues apparaissant dans une ou\n plusieurs séquences et
    renverra une collection d'alignements multiples\n locaux pour chacune d'entre
    elles.\n"
  release: sid
  description_md5: a4af9732493dab9dac9eed761a23a635
  license: unknown
  blend: debian-med
