about:
  home: http://metacpan.org/pod/Config-General
  license: perl_5
  summary: Generic Config Module
build:
  noarch: generic
  number: 0
  run_exports:
  - None
package:
  name: perl-config-general
  version: '2.67'
requirements:
  build:
  - make
  host:
  - perl
  - perl-pathtools
  - perl-extutils-makemaker
  run:
  - perl
  - perl-pathtools
source:
  sha256: 473d65127b23dac0e8039c01e28bc4072cb9a6e93e81a1ea4893cea08c698db0
  url: https://cpan.metacpan.org/authors/id/T/TL/TLINDEN/Config-General-2.67.tar.gz
