about:
  dev_url: https://github.com/galaxyproject/galaxy-job-config-init
  home: https://github.com/galaxyproject/galaxy-job-config-init
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Galaxy configuration.
build:
  noarch: python
  number: 0
  run_exports:
  - None
  script: -m pip install . -vvv --no-deps --no-build-isolation --no-cache-dir
package:
  name: galaxy-job-config-init
  version: 0.1.3
requirements:
  host:
  - python >=3.7
  - setuptools
  - pip
  run:
  - python >=3.7
  - typing_extensions
  - jinja2
  - pyyaml
  - backports.strenum
source:
  sha256: d0c0bd71f39e0491672bd8782ccc1527ea003442f614fff9934ad2ef131b0322
  url: https://pypi.org/packages/source/g/galaxy-job-config-init/galaxy_job_config_init-0.1.3.tar.gz
test:
  imports:
  - gxjobconfinit
