about:
  description: StringDecomposer (SD) algorithm takes the set of monomers and a long
    error-prone read (or a genomic segment) and partitions this read into distinct
    monomers.
  dev_url: https://github.com/ablab/stringdecomposer
  home: https://github.com/ablab/stringdecomposer
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: A tool for decomposing of strings into a set of given monomers.
build:
  entry_points:
  - stringdecomposer = stringdecomposer.main:main
  number: 5
  run_exports:
  - None
  script:
  - export LDFLAGS="${LDFLAGS} -L${PREFIX}/lib"
  - export CPPFLAGS="${CPPFLAGS} -I${PREFIX}/include"
  - export CXXFLAGS="${CXXFLAGS} -O3"
  - -m pip install . -vvv --no-build-isolation --no-deps --no-cache-dir
  skip: true
extra:
  additional-platforms:
  - linux-aarch64
  - osx-arm64
package:
  name: stringdecomposer
  version: 1.1.2
requirements:
  build:
  - None
  - make
  - pkg-config
  host:
  - python
  - pip
  - llvm-openmp
  - libgomp
  run:
  - python
  - biopython
  - pandas
  - python-edlib
  - llvm-openmp
  - libgomp
source:
  sha256: 6bcd81d1762edc39c9125965f2b7a3d6d7bf39eb2bd043eaffc732795754968a
  url: https://github.com/ablab/stringdecomposer/archive/v1.1.2.tar.gz
test:
  commands:
  - stringdecomposer -h | grep -q "Decomposes string into blocks alphabet"
