name: 'debug bio.tools json'

on:
  workflow_dispatch:

jobs:
  test-jq:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        
      - name: reformat json to a predictable format with jq and sponge
        if: ${{ !endsWith(github.head_ref, '__delete') }}
        shell: bash
        run: |
          sudo apt-get update -y
          sudo apt-get install moreutils
          jq --indent 4 'walk( if type == "array" then sort else . end )' data/metabolink/metabolink.biotools.json
          echo "Processed data/metabolink/metabolink.biotools.json!"
